config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root "clockings#index"


resources :clockings

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/clocking.rb
class Clocking < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clockings_controller.rb
class ClockingsController < ApplicationController

  def index
    @logs = Clocking.all
    @logs = @logs.order(time: :desc)
  end

  def new
    @clocking = Clocking.new
  end

  def create
    @clocking = Clocking.new(clocking_params)
    @clocking.time = Time.now
    if @clocking.save
      flash[:success] = "Clocked #{params[:clocking][:clock_type]} succesfully"
      redirect_to clockings_path
    else
      render :new
    end
  end

  private

  def clocking_params
    params.require(:clocking).permit(:name , :clock_type)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clockings_helper.rb
module ClockingsHelper
end

app/views/clockings/index.html.erb
<style>

table tr td, table tr th{
  border: 1px solid black;
}
table{
  width:500px;
  border-collapse: collapse;
}

</style>

  <% if @logs %>
      <table>
        <tr>
          <th>Name</th>
          <th>Clock Type</th>
          <th>Time</th>
        </tr>
    <% @logs.each do |log| %>

      <tr>
        <td><%= log.name %></td>
        <td><%= log.clock_type %></td>
        <td><%= log.time %></td>
      </tr>
    <% end %>
      </table>
  <% else %>
    <p>Logs are empty</p>
<% end %>

app/views/clockings/new.html.erb
<style>



</style>

<%= form_for(@clocking) do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <br/>
  <br/>

  <%= f.label :clock_type %>
  <%= f.select :clock_type , options_for_select([['in'],['out']])%>
  <br/>
  <br/>
  <br/>
  <%= f.submit('Submit') %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timekeeper</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
      a{
        text-decoration:none;
        background-color:#ebebeb;
        margin-right: 20px;
        padding:5px;
      }
      a:hover{
        background-color: grey;
        color:white;
       }

      #msg{
        width:400px;
        background-color:#ebebeb;
        margin-bottom:30px;
        }
    </style>

  </head>

  <body>
    <h1>Timekeeper</h1>

    <% flash.each do |name,msg| %>
      <div id="msg">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg %>
      </div>
    <% end %>

    <%= link_to "View logs" , clockings_path%>
    <%= link_to "Clock in/out" , new_clocking_path %>
    <br/>
    <br/>
    <%= yield %>
  </body>
</html>